# crds/*.yaml are not templated
# See: https://helm.sh/docs/topics/chart_best_practices/custom_resource_definitions/#install-a-crd-declaration-before-using-the-resource
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusters.cluster-operator.infobloxopen.github.com
spec:
  group: cluster-operator.infobloxopen.github.com
  names:
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
    shortNames:
    - cl
  scope: Namespaced    
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST
                resource this object represents. Servers may infer this from
                the endpoint the client submits requests to. Cannot be updated.
                In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              type: object
              description: ClusterSpec defines the desired state of Cluster 
              properties:
                name:
                  type: string
                config: 
                  type: string
                Protected:
                  type: string
                  default: "IGNORE FOR NOW"
            status:
              description: ClusterStatus defines the observed state of Cluster 
              type: object