{{- $fullName := include "cluster-operator.fullname" . -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: cluster-operator
roleRef:
  kind: Role
  name: cluster-operator
  apiGroup: rbac.authorization.k8s.io
