apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ .Release.Name }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "cluster-operator.labels" . | indent 4 }}
spec:
  selfSigned: {}
---    
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Release.Name }}-webhook-server-tls
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "cluster-operator.labels" . | indent 4 }}
spec:
  dnsNames:
  - "{{ .Release.Name }}-cluster-validator.{{ .Release.Namespace }}.svc"
  secretName: {{ .Release.Name }}-webhook-server-tls
  usages:
    - server auth
    - client auth
  issuerRef:
    name: {{ .Release.Name }}-selfsigned-issuer