apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cluster-validator
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "cluster-operator.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "cluster-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 443
      targetPort: webhook-api
