apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "cluster-operator.labels" . | indent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "cluster-operator.fullname" . }}
  labels:
{{ include "cluster-operator.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  - "cluster-operator.infobloxopen.github.com"
  resources:
  - services
  - pods
  - secrets
  - clusters
  - clusters/status
  - events
  - configmaps
  - replicasets
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: {{ include "cluster-operator.fullname" . }}
  labels:
{{ include "cluster-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cluster-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "cluster-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  