apiVersion: v1
kind: Service
metadata:
  name: cluster-validator
  namespace: operator
spec:
  selector:
    app.kubernetes.io/name: cluster-operator
  ports:
    - port: 443
      targetPort: webhook-api
